### ISSUE TITLE
Variable "await" is a reserved word in ES6 module code, breaking transpilation in some contexts

### ISSUE THREAD

**Issue by mitchhentges** [greim/await.js#3]
[edit by @greim] Previously titled:

> Cannot use project with transitive dependency `await.js` with Rollup

Rollup is a module bundler that converts ES2015 code into a single bundle, and also removes unused libraries. In order for it to put `node_modules` dependencies into that final bundle, the dependencies need to be converted to ES2015 (redundant, yeah, 'cause Rollup converts it right back). https://github.com/rollup/rollup-plugin-commonjs is the plugin used to convert the dependencies.

When the forwards-transpiler runs into `await.js`, it chokes, because `await` is a reserved word.
```
The keyword 'await' is reserved (354:13) in {...}node_modules/await/await.js
```

I'm going to personally solve this by doing something else _rather than_ forwards-transpiling, then backwards-transpiling, but other people might have the same issue without the flexibility to use another solution

**Comment by greim** [comment]
Thanks for the report. To make sure I understand, would it solve it if the internal `await` variable was simply renamed to `_await` or something? If so, I'd like to re-title this issue:

> Variable "await" is a reserved word in ES6 module code, breaking transpilation in some contexts

Also if so, I'm happy to accept a PR, otherwise I'll get around to this eventually :)

**Comment by mitchhentges** [comment]
Sweet, yeah, that would fix it. I'll purpose a pr in two days, tops.
